INSERT INTO waf_rules (name, rule_key, description, category, pattern, target, action, severity, status, score) VALUES
('SQLi UNION SELECT', 'sqli_union_select', 'Detects UNION SELECT probes.', 'sql_injection', '\\bunion\\s+(all\\s+)?select\\b', 'all', 'block', 'critical', TRUE, 50),
('SQLi Boolean OR', 'sqli_or_boolean', 'Detects OR 1=1 style boolean SQL injection.', 'sql_injection', '\\bor\\s+1\\s*=\\s*1\\b', 'all', 'block', 'critical', TRUE, 45),
('SQLi Boolean AND', 'sqli_and_boolean', 'Detects AND 1=1 style boolean SQL injection.', 'sql_injection', '\\band\\s+1\\s*=\\s*1\\b', 'all', 'block', 'high', TRUE, 35),
('SQLi DROP TABLE', 'sqli_drop_table', 'Detects destructive DROP TABLE statements.', 'sql_injection', '\\bdrop\\s+table\\b', 'all', 'block', 'critical', TRUE, 60),
('SQLi Information Schema', 'sqli_information_schema', 'Detects information_schema enumeration.', 'sql_injection', '\\binformation_schema\\b', 'all', 'block', 'high', TRUE, 35),
('SQLi Time Delay', 'sqli_time_delay', 'Detects SLEEP or BENCHMARK SQL timing probes.', 'sql_injection', '\\b(sleep|benchmark)\\s*\\(', 'all', 'block', 'critical', TRUE, 50),
('SQLi File Access', 'sqli_file_access', 'Detects LOAD_FILE or INTO OUTFILE usage.', 'sql_injection', '\\b(load_file|into\\s+outfile)\\b', 'all', 'block', 'critical', TRUE, 50),
('SQLi Comment Abuse', 'sqli_comment_abuse', 'Detects common SQL comment abuse.', 'sql_injection', '(/\\*|\\*/|--\\s|#)', 'query', 'block', 'medium', TRUE, 20),
('XSS Script Tag', 'xss_script_tag', 'Detects script tag injection.', 'xss', '<\\s*/?\\s*script\\b', 'all', 'block', 'critical', TRUE, 50),
('XSS JavaScript URI', 'xss_javascript_uri', 'Detects javascript: URI injection.', 'xss', 'javascript\\s*:', 'all', 'block', 'high', TRUE, 35),
('XSS Event Handler', 'xss_event_handler', 'Detects onerror/onload event handlers.', 'xss', '\\bon(error|load)\\s*=', 'all', 'block', 'high', TRUE, 35),
('XSS Iframe', 'xss_iframe', 'Detects iframe injection attempts.', 'xss', '<\\s*iframe\\b', 'all', 'block', 'medium', TRUE, 25),
('XSS SVG Onload', 'xss_svg_onload', 'Detects SVG onload payloads.', 'xss', '<\\s*svg\\b[^>]*\\bonload\\s*=', 'all', 'block', 'high', TRUE, 35),
('XSS Cookie Theft', 'xss_document_cookie', 'Detects document.cookie access.', 'xss', 'document\\s*\\.\\s*cookie', 'all', 'block', 'high', TRUE, 35),
('XSS Eval Alert', 'xss_eval_alert', 'Detects eval or alert JavaScript payloads.', 'xss', '\\b(eval|alert)\\s*\\(', 'all', 'block', 'medium', TRUE, 20),
('Path Traversal Dots', 'path_traversal_dots', 'Detects ../ and ..\\ traversal.', 'path_traversal', '(\\.\\./|\\.\\.\\\\)', 'all', 'block', 'high', TRUE, 35),
('Path Traversal Encoded', 'path_traversal_encoded', 'Detects encoded dot-dot traversal.', 'path_traversal', '(%2e%2e|%252e%252e)', 'all', 'block', 'high', TRUE, 35),
('Path Sensitive Files', 'path_sensitive_files', 'Detects common OS sensitive file probes.', 'path_traversal', '(/etc/passwd|boot\\.ini|win\\.ini)', 'all', 'block', 'critical', TRUE, 50),
('Command Chaining', 'cmd_chain', 'Detects shell command chaining probes.', 'command_injection', '(;\\s*cat\\b|&&\\s*whoami\\b|\\|\\s*whoami\\b)', 'all', 'block', 'critical', TRUE, 50),
('Command Substitution', 'cmd_substitution', 'Detects backtick or dollar command substitution.', 'command_injection', '(`[^`]+`|\\$\\([^)]*\\))', 'all', 'block', 'high', TRUE, 35),
('Command Shells', 'cmd_shells', 'Detects shell executable references.', 'command_injection', '(/bin/bash|powershell|cmd\\.exe)', 'all', 'block', 'critical', TRUE, 50),
('Scanner User Agent', 'scanner_user_agent', 'Detects common scanner user agents.', 'scanner', '(sqlmap|nikto|nmap|masscan|dirbuster|gobuster|ffuf|wpscan|acunetix|nessus|openvas|burpsuite)', 'user_agent', 'block', 'critical', TRUE, 60),
('Suspicious Dotfile Request', 'file_dotfile_request', 'Detects requests for hidden config repositories.', 'file_attack', '(\\.env|\\.git)(/|$)', 'url', 'block', 'critical', TRUE, 60),
('Suspicious PHP Config Request', 'file_php_config_request', 'Detects common PHP config and info probes.', 'file_attack', '(wp-config\\.php|phpinfo\\.php|config\\.php)$', 'url', 'block', 'high', TRUE, 35),
('Suspicious Database Backup Request', 'file_database_backup_request', 'Detects common database backup file probes.', 'file_attack', '(backup\\.sql|database\\.sql)$', 'url', 'block', 'critical', TRUE, 50)
ON DUPLICATE KEY UPDATE
name = VALUES(name),
description = VALUES(description),
category = VALUES(category),
pattern = VALUES(pattern),
target = VALUES(target),
action = VALUES(action),
severity = VALUES(severity),
score = VALUES(score);
