CREATE TABLE IF NOT EXISTS plugins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  version VARCHAR(40) NOT NULL DEFAULT '1.0.0',
  description TEXT NULL,
  author VARCHAR(160) NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  installed BOOLEAN NOT NULL DEFAULT TRUE,
  manifest JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS plugin_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  plugin_id INT UNSIGNED NOT NULL,
  `key` VARCHAR(120) NOT NULL,
  value TEXT NULL,
  value_type ENUM('string','number','boolean','json') NOT NULL DEFAULT 'string',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_plugin_setting (plugin_id, `key`),
  CONSTRAINT fk_plugin_settings_plugin FOREIGN KEY (plugin_id) REFERENCES plugins(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plugin_hooks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  plugin_id INT UNSIGNED NOT NULL,
  hook VARCHAR(120) NOT NULL,
  handler VARCHAR(180) NOT NULL,
  priority INT NOT NULL DEFAULT 10,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_plugin_hooks_plugin FOREIGN KEY (plugin_id) REFERENCES plugins(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plugin_migrations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  plugin_id INT UNSIGNED NOT NULL,
  migration VARCHAR(180) NOT NULL,
  batch INT NOT NULL DEFAULT 1,
  ran_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_plugin_migration (plugin_id, migration),
  CONSTRAINT fk_plugin_migrations_plugin FOREIGN KEY (plugin_id) REFERENCES plugins(id) ON DELETE CASCADE
);
