ALTER TABLE themes
  ADD COLUMN IF NOT EXISTS manifest JSON NULL AFTER preview_image,
  ADD COLUMN IF NOT EXISTS parent_slug VARCHAR(180) NULL AFTER slug;

ALTER TABLE theme_settings
  ADD COLUMN IF NOT EXISTS custom_css MEDIUMTEXT NULL AFTER favicon,
  ADD COLUMN IF NOT EXISTS custom_js MEDIUMTEXT NULL AFTER custom_css;
