ALTER TABLE media
  ADD COLUMN IF NOT EXISTS thumbnail_path VARCHAR(500) NULL AFTER file_path,
  ADD COLUMN IF NOT EXISTS medium_path VARCHAR(500) NULL AFTER thumbnail_path,
  ADD COLUMN IF NOT EXISTS large_path VARCHAR(500) NULL AFTER medium_path,
  ADD COLUMN IF NOT EXISTS width INT UNSIGNED NULL AFTER file_size,
  ADD COLUMN IF NOT EXISTS height INT UNSIGNED NULL AFTER width,
  ADD COLUMN IF NOT EXISTS duration FLOAT NULL AFTER height,
  ADD COLUMN IF NOT EXISTS alt_text VARCHAR(255) NULL AFTER duration,
  ADD COLUMN IF NOT EXISTS caption VARCHAR(500) NULL AFTER alt_text,
  ADD COLUMN IF NOT EXISTS description TEXT NULL AFTER caption;
